asp practica con sql/Models/ErrorViewModel.cs
namespace asp_practica_con_sql.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

asp practica con sql/Models/PersonasContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace asp_practica_con_sql.Models;

public partial class PersonasContext : DbContext
{
    public PersonasContext()
    {
    }

    public PersonasContext(DbContextOptions<PersonasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TablaGenero> TablaGeneros { get; set; }

    public virtual DbSet<TablaPersona> TablaPersonas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=DESKTOP-NDND5BN; DataBase=personas; Trusted_Connection=True; TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TablaGenero>(entity =>
        {
            entity.ToTable("tabla_generos");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.NombreGenero)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("nombre_genero");
        });

        modelBuilder.Entity<TablaPersona>(entity =>
        {
            entity.ToTable("tabla_personas");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.EdadPersona).HasColumnName("edad_persona");
            entity.Property(e => e.IdGenero).HasColumnName("ID_GENERO");
            entity.Property(e => e.NombrePersona)
                .HasMaxLength(50)
                .IsFixedLength()
                .HasColumnName("nombre_persona");

            entity.HasOne(d => d.IdGeneroNavigation).WithMany(p => p.TablaPersonas)
                .HasForeignKey(d => d.IdGenero)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tabla_personas_tabla_generos");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

asp practica con sql/Models/TablaGenero.cs
using System;
using System.Collections.Generic;

namespace asp_practica_con_sql.Models;

public partial class TablaGenero
{
    public int Id { get; set; }

    public string NombreGenero { get; set; } = null!;

    public virtual ICollection<TablaPersona> TablaPersonas { get; set; } = new List<TablaPersona>();
}

asp practica con sql/Models/TablaPersona.cs
using System;
using System.Collections.Generic;

namespace asp_practica_con_sql.Models;

public partial class TablaPersona
{
    public int Id { get; set; }

    public string? NombrePersona { get; set; }

    public int IdGenero { get; set; }

    public int? EdadPersona { get; set; }

    public virtual TablaGenero IdGeneroNavigation { get; set; } = null!;
}

asp practica con sql/Models/ViewModels/PersonaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace asp_practica_con_sql.Models.ViewModels
{
    public class PersonaViewModel
    {
        [Required]
        [Display(Name="Nombre")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Edad")]
        public int Age { get; set; }

        [Required]
        [Display(Name = "Genero")]
        public int GenderID { get; set; }

    }
}

asp practica con sql/Controllers/HomeController.cs
using asp_practica_con_sql.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace asp_practica_con_sql.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

asp practica con sql/Controllers/PersonasController.cs
using asp_practica_con_sql.Models;
using asp_practica_con_sql.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace asp_practica_con_sql.Controllers
{
    public class PersonasController : Controller
    {
        private readonly PersonasContext _personasContext;
        public PersonasController(PersonasContext personasContext)
        {
            _personasContext = personasContext;
        }

        public async Task<IActionResult> Index()
        {
            var persona = _personasContext.TablaPersonas.Include(p => p.IdGeneroNavigation);
            return View(await persona.ToListAsync());
        }
        public IActionResult Create()
        {
            ViewData["Genero"] = new SelectList(_personasContext.TablaGeneros, "Id", "NombreGenero");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var persona = new TablaPersona()
                {
                    NombrePersona = model.Name,
                    EdadPersona = model.Age,
                    IdGenero = model.GenderID
                };
                _personasContext.Add(persona);
                await _personasContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewData["Genero"] = new SelectList(_personasContext.TablaGeneros, "Id", "NombreGenero",model.GenderID);
            return View(model);
        }
    }
}

asp practica con sql/Views/GeneroControles/Index.cshtml
@model List<TablaGenero>

<h1>Generos</h1>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var genero in Model)
        {
            <tr>
                <td>@Html.DisplayFor(a=>genero.Id)</td>
                <td>@Html.DisplayFor(a=>genero.NombreGenero)</td>
            </tr>
        }
    </tbody>
</table>

asp practica con sql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

asp practica con sql/Views/Personas/Create.cshtml
@using asp_practica_con_sql.Models.ViewModels
@model PersonaViewModel
<h1>Crear Persona</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input type="number" min="1" asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>

            <div>
                <label asp-for="GenderID"></label>
                <select asp-for="GenderID" class="form-control" asp-items="ViewBag.Genero"></select>
                <span asp-validation-for="GenderID" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Crear" class="btn-primary" />
            </div>

        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

asp practica con sql/Views/Personas/Index.cshtml
@model List<TablaPersona>
<h1>Personas</h1>
<p>
    <a asp-action="Create">Crear Persona</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Edad</th>
            <th>Genero</th>
        </tr>
    </thead>
    <tbody>
       
        @foreach (var personas in Model)
        {
            <tr>
                <td>@Html.DisplayFor(p=>personas.Id)</td>
                <td>@Html.DisplayFor(p=>personas.NombrePersona)</td>
                <td>@Html.DisplayFor(p=>personas.EdadPersona)</td>
                <td>@Html.DisplayFor(p=>personas.IdGeneroNavigation.NombreGenero)</td>
            </tr>
        }
    </tbody>
</table>

asp practica con sql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - asp_practica_con_sql</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asp_practica_con_sql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Registro de Personas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GeneroControles" asp-action="Index">Genero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - asp_practica_con_sql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>